# Generated by Django 4.2.18 on 2025-04-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price_new',
            field=models.IntegerField(default=0),
        ),
    ]
