# Generated by Django 4.2.18 on 2025-04-11 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_color_var_alter_products_size_var'),
        ('accounts', '0006_cartitem_price_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product_image'),
        ),
    ]
