# Generated by Django 4.2.18 on 2025-03-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_colors_type_size_type_products_color_var_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color_var',
            field=models.ManyToManyField(blank=True, to='products.colors_type'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size_var',
            field=models.ManyToManyField(blank=True, to='products.size_type'),
        ),
    ]
